// <auto-generated />
namespace BTL_LT_UD_WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class duc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(duc));
        
        string IMigrationMetadata.Id
        {
            get { return "202112201312282_duc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
